# Generated by Django 5.1.3 on 2024-11-18 08:23

import travel_project.user_profile.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='facilities',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='photo',
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(default=1, max_length=15, validators=[travel_project.user_profile.validators.validate_phone_number]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='payment_method',
            field=models.CharField(choices=[('Credit card', 'Credit card'), ('Paypal', 'Paypal'), ('Bank transfer', 'Bank transfer'), ('Crypto', 'Crypto')], max_length=30),
        ),
    ]
