# Generated by Django 5.1.3 on 2024-11-17 13:44

import travel_project.flight.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=10, unique=True)),
                ('destinations', models.CharField(max_length=40)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[travel_project.flight.validators.flight_price])),
                ('airlines', models.CharField(choices=[('Qatar Airways', 'Qatar Airways'), ('Ryanair', 'Ryanair'), ('British Airways', 'British Airways'), ('Emirates', 'Emirates'), ('Singapore Airlines', 'Singapore Airlines'), ('Lufthansa', 'Lufthansa')], max_length=30)),
                ('airlines_logo', models.URLField()),
                ('is_direct', models.BooleanField()),
            ],
        ),
    ]
