# Generated by Django 5.1.3 on 2024-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('flag', models.URLField()),
                ('continent', models.CharField(choices=[('Africa', 'Africa'), ('Asia', 'Asia'), ('Europe', 'Europe'), ('North America', 'North America'), ('South America', 'South America'), ('Australia and Oceania', 'Australia and Oceania'), ('Antarctica', 'Antarctica')], max_length=40)),
                ('description', models.TextField(blank=True, null=True)),
                ('capital', models.CharField(max_length=100)),
                ('population', models.PositiveBigIntegerField()),
                ('official_language', models.CharField(max_length=100)),
                ('currency', models.CharField(max_length=50)),
                ('is_visited', models.BooleanField(default=False)),
            ],
        ),
    ]
