# Generated by Django 5.1.3 on 2024-11-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('country', models.CharField(max_length=40)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('attractions', models.TextField()),
                ('image', models.URLField()),
                ('best_time_to_visit', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
